apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-operator-secret-reader
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-operator-secret-reader-binding
  namespace: external-secrets
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
roleRef:
  kind: Role
  name: external-secrets-operator-secret-reader
  apiGroup: rbac.authorization.k8s.io
