apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sherpany-db-envs
  namespace: sherpany-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secretstore
  target:
    name: sherpany-db-envs
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: sherpany-db-envs
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: sherpany-db-envs
        property: DB_PASSWORD
    - secretKey: DB_HOST
      remoteRef:
        key: sherpany-db-envs
        property: DB_HOST
    - secretKey: DB_NAME
      remoteRef:
        key: sherpany-db-envs
        property: DB_NAME
