apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sherpany-app
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: sherpany-app
  namespaceSelector:
    matchNames:
      - sherpany-app
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
